import type { DocumentContent } from './blocks'

/**
 * The content of each document, transcribed from the source pack.
 *
 * Transcribed, not written. Every heading, clause and table row here
 * comes from the supplied Compliance & Safety Pack. Nothing in this file
 * is Doorlink's own drafting, and nothing may be added to it that is
 * not in the source: these are documents a business signs and hands to
 * a client or an insurer, and an invented clause in one of them is a
 * false statement made in that business's name.
 *
 * Where the source flags a caveat — a jurisdiction note, a "confirm
 * against the manual" panel, a section needing professional review —
 * that flag is carried through rather than tidied away. The caveats are
 * the parts most worth keeping.
 */

export const DOCUMENT_CONTENT: Record<string, DocumentContent> = {
  'DL-BUS-001': {
    code: 'DL-BUS-001',
    intro:
      'Complete this form once. Every other document in the DoorLink Compliance & Safety pack uses the same business details, so having them recorded and approved here keeps the whole system consistent.',
    blocks: [
      { kind: 'heading', number: '01', title: 'Business Details' },
      { kind: 'businessDetails' },
      { kind: 'heading', number: '02', title: 'Key People' },
      {
        kind: 'fields',
        rows: [
          { label: 'Business owner / director', value: 'ownerName' },
          { label: 'Operations manager', value: 'operationsManager' },
          { label: 'Compliance contact', value: 'complianceContact' },
          { label: 'Primary site contact', value: 'primarySiteContact' },
          { label: 'Emergency contact (name)', value: 'emergencyContactName' },
          { label: 'Emergency contact number', value: 'emergencyContactNumber' },
          { label: 'Nominated first aid officer', value: 'firstAidOfficer' },
        ],
      },
      { kind: 'heading', number: '03', title: 'Jurisdiction, Licences and Insurance' },
      {
        kind: 'para',
        text: 'Record the state or territory the business operates in and the regulator that applies. Where work is performed across more than one jurisdiction, list each one and confirm the licensing requirements separately.',
      },
      {
        kind: 'fields',
        rows: [
          { label: 'State / territory', value: 'state' },
          { label: 'Applicable WHS regulator', value: 'whsRegulator' },
          { label: 'Trade licence number', value: 'tradeLicenceNumber' },
          { label: 'Electrical licence number (if applicable)', value: 'electricalLicenceNumber' },
          { label: 'Other registration / certification', value: 'otherRegistration' },
          { label: 'Public liability insurer and policy number', value: 'publicLiabilityPolicy' },
          { label: 'Public liability expiry date', value: 'publicLiabilityExpiry' },
          { label: 'Workers compensation policy number', value: 'workersCompPolicy' },
          { label: 'Workers compensation expiry date', value: 'workersCompExpiry' },
        ],
      },
      {
        kind: 'important',
        text: 'Insurance and licence details change. Diarise each expiry date above and review this page whenever a policy is renewed or a licence is added.',
      },
      { kind: 'heading', number: '04', title: 'Document Register' },
      {
        kind: 'para',
        text: 'Record the version of each document your business is currently using. Reissue the affected documents whenever a policy, procedure or legislative reference changes.',
      },
      {
        kind: 'table',
        head: ['Doc no.', 'Document', 'Version', 'Effective', 'Review due', 'Approved by'],
        rows: [
          ['DL-BUS-001', 'Business Information & Document Register', '', '', '', ''],
          ['DL-COMP-001', 'Contractor Compliance Requirements & Declaration', '', '', '', ''],
          ['DL-WHS-001', 'Workplace Health & Safety Policy Statement', '', '', '', ''],
          ['DL-WHS-002', 'Health & Safety Management Plan', '', '', '', ''],
          ['DL-WHS-003', 'WHS Responsibilities Statement', '', '', '', ''],
          ['DL-WHS-004', 'WHS Legislation & Continuous Improvement Statement', '', '', '', ''],
          ['DL-WHS-005', 'Safety Induction Statement & Record', '', '', '', ''],
          ['DL-WHS-006', 'Drug, Alcohol & Fatigue Management Policy', '', '', '', ''],
          ['DL-WHS-007', 'Vehicle First Aid Kit Policy & Compliance Log', '', '', '', ''],
          ['DL-RISK-001', 'Risk Register & Risk Assessment', '', '', '', ''],
          ['DL-SWMS-001', 'Safe Work Method Statement', '', '', '', ''],
          ['DL-INSP-001', 'Master Maintenance Checklist', '', '', '', ''],
          ['DL-INC-001', 'Work Incident, Near Miss & Hazard Report', '', '', '', ''],
          ['DL-EMG-001', 'Business Continuity & Emergency Management Plan', '', '', '', ''],
          ['DL-JOB-001', 'Warranty Certificate', '', '', '', ''],
        ],
      },
      { kind: 'heading', number: '05', title: 'Revision History' },
      {
        kind: 'blankRows',
        head: ['Version', 'Date', 'Change made', 'Changed by', 'Approved by'],
        count: 5,
      },
      { kind: 'heading', number: '06', title: 'Approval' },
      { kind: 'signature', parties: ['Prepared by', 'Approved by'] },
    ],
  },

  'DL-COMP-001': {
    code: 'DL-COMP-001',
    intro:
      'Issue this document to every contractor and subcontractor before they start work. It sets out the legislation they must work under, the status of their engagement, and the evidence they must provide.',
    blocks: [
      { kind: 'heading', number: '01', title: 'Business Details' },
      { kind: 'businessDetails' },
      { kind: 'documentControl' },
      { kind: 'heading', number: '02', title: 'Legislative Compliance' },
      {
        kind: 'legislation',
        lead: 'All contractors and subcontractors engaged by the business must comply with all applicable Commonwealth and state legislation, including but not limited to:',
      },
      { kind: 'heading', number: '03', title: 'Contractor Status' },
      {
        kind: 'para',
        text: 'Contractors acknowledge that they are independent contractors operating their own business, and are responsible for maintaining all licences, insurances, taxation obligations, superannuation obligations where applicable, registrations and certifications required to lawfully perform the contracted works.',
      },
      {
        kind: 'para',
        text: 'Contractors acknowledge that their engagement does not constitute an employment relationship unless otherwise determined under applicable legislation.',
      },
      { kind: 'heading', number: '04', title: 'Fair Work Compliance' },
      {
        kind: 'bullets',
        items: [
          'The business is committed to complying with the Fair Work Act 2009 (Cth) and all applicable workplace laws.',
          'Sham contracting arrangements are prohibited. The business will not knowingly misrepresent an employment relationship as an independent contracting arrangement.',
          'Contractors must ensure that any workers they engage are lawfully engaged and entitled to work in Australia.',
        ],
      },
      { kind: 'heading', number: '05', title: 'Work Health and Safety' },
      {
        kind: 'para',
        text: 'All contractors must take reasonable care for their own health and safety and for the safety of others who may be affected by their acts or omissions. Contractors must:',
      },
      {
        kind: 'bullets',
        items: [
          'Follow all site-specific safety requirements.',
          'Comply with approved Safe Work Method Statements (SWMS).',
          'Use appropriate Personal Protective Equipment (PPE).',
          'Report hazards, incidents and near misses immediately.',
          'Ensure all plant, tools and equipment are maintained and safe for use.',
        ],
      },
      {
        kind: 'heading',
        number: '06',
        title: 'Insurance and Documentation Required Before Starting Work',
      },
      {
        kind: 'para',
        text: 'Current copies of the following must be provided and verified before the contractor attends site. Engagements may be suspended or terminated where documentation has expired or has not been provided.',
      },
      {
        kind: 'table',
        head: ['Document', 'Provided', 'Expiry date', 'Verified by'],
        rows: [
          ['Public liability insurance', '', '', ''],
          ['Workers compensation insurance (where required)', '', '', ''],
          ['Relevant trade licence', '', '', ''],
          ['Electrical licence (if applicable)', '', '', ''],
          ['Construction induction card (White Card)', '', '', ''],
          ['High-risk work licence (specify class)', '', '', ''],
          ['Plant operator licence / VOC (specify)', '', '', ''],
          ['Company SWMS for the contracted works', '', '', ''],
          ['Vehicle registration and insurance', '', '', ''],
          ['Other (specify)', '', '', ''],
        ],
      },
      { kind: 'heading', number: '07', title: 'Contractor Declaration' },
      {
        kind: 'para',
        text: 'I declare that I have read and understood the compliance requirements set out in this document, that the documentation I have provided is current and accurate, and that I will notify the business immediately if any licence, insurance or certification lapses or is cancelled.',
      },
      {
        kind: 'fields',
        rows: [
          { label: 'Full name (print)', value: null },
          { label: 'Contracting company name', value: null },
          { label: 'Residential address', value: null },
          { label: 'ABN', value: null },
          { label: 'Phone', value: null },
          { label: 'Email', value: null },
        ],
      },
      { kind: 'signature', parties: ['Contractor', 'Accepted for the business'] },
    ],
  },

  'DL-WHS-001': {
    code: 'DL-WHS-001',
    intro:
      'A signed policy statement is usually the first document a client, principal contractor or insurer asks to see. Complete the business details, have it approved, and display it where workers can read it.',
    blocks: [
      { kind: 'heading', number: '01', title: 'Business Details' },
      { kind: 'businessDetails' },
      { kind: 'documentControl' },
      { kind: 'heading', number: '02', title: 'Policy Statement' },
      {
        kind: 'para',
        text: 'This business is committed to providing and maintaining a safe and healthy workplace for all workers, subcontractors, clients, visitors and members of the public. This policy is built around compliance with the Work Health and Safety Act 2011, the Work Health and Safety Regulation 2017 and the relevant SafeWork Codes of Practice applicable in the jurisdiction recorded in Section 01.',
      },
      { kind: 'heading', number: '03', title: 'Our Commitments' },
      {
        kind: 'bullets',
        items: [
          'Provide safe work systems covering installation, repairs, maintenance and emergency works.',
          'Identify hazards, assess risks and implement appropriate control measures.',
          'Ensure all workers are trained, competent and supervised in safe work practices.',
          'Maintain safe plant, tools and equipment, including lock-out / tag-out procedures.',
          'Consult with workers and subcontractors on safety matters and improvements.',
          'Regularly review safety procedures, incidents and near misses to ensure continual improvement.',
          'Ensure SWMS, health and safety management plans, JSA tables and emergency procedures are followed on all worksites.',
        ],
      },
      { kind: 'heading', number: '04', title: 'Responsibilities' },
      {
        kind: 'table',
        head: ['Role', 'Responsibility'],
        rows: [
          [
            'Management',
            'Implement WHS systems, provide training and equipment, and ensure full compliance with WHS legislation.',
          ],
          [
            'Workers',
            'Follow procedures, use PPE, report hazards, and stop work immediately if a task is unsafe.',
          ],
          ['Subcontractors', 'Comply with this policy and follow all site safety rules.'],
        ],
      },
      { kind: 'heading', number: '05', title: 'Continuous Improvement' },
      {
        kind: 'para',
        text: 'The business maintains a systematic review process. WHS performance is evaluated through audits, toolbox talks, incident reviews, equipment inspections and worker consultation, so that WHS systems remain effective, current and aligned with regulation and industry practice.',
      },
      { kind: 'heading', number: '06', title: 'Statement of Commitment' },
      {
        kind: 'para',
        text: 'The business will actively work to eliminate or reduce risks, promote safe behaviour, and ensure every worker returns home safely every day.',
      },
      { kind: 'signature', parties: ['Director / responsible officer'] },
    ],
  },

  'DL-WHS-002': {
    code: 'DL-WHS-002',
    intro:
      'The Health & Safety Management Plan is the parent document for your safety system. It states how hazards are controlled, who is responsible, and what training workers must hold before they attend site.',
    blocks: [
      { kind: 'heading', number: '01', title: 'Business Details' },
      { kind: 'businessDetails' },
      { kind: 'documentControl' },
      { kind: 'heading', number: '02', title: 'Purpose and Objectives' },
      {
        kind: 'para',
        text: 'This plan outlines the safety policies, responsibilities and procedures required to ensure safe operations for all employees and subcontractors. It aligns with the WHS Act 2011, WHS Regulation 2017 and the SafeWork Codes of Practice applicable in the jurisdiction recorded in Section 01.',
      },
      {
        kind: 'bullets',
        items: [
          'Prevent injuries, incidents and property damage.',
          'Comply with all applicable WHS legislation.',
          'Provide safe work environments for workers and clients.',
          'Ensure adequate training, supervision, PPE and risk controls.',
        ],
      },
      { kind: 'heading', number: '03', title: 'Safety Responsibilities' },
      {
        kind: 'table',
        head: ['Role', 'Responsibility'],
        rows: [
          [
            'Management',
            'Implement this plan, ensure training is delivered, review incidents, and provide safe equipment.',
          ],
          ['Workers', 'Follow procedures, report hazards, use PPE, and stop unsafe work.'],
          ['Subcontractors', "Comply with the business's WHS requirements and applicable regulations."],
        ],
      },
      { kind: 'heading', number: '04', title: 'Risk Management Process' },
      {
        kind: 'bullets',
        items: [
          'Identify hazards — site conditions, electrical, working at heights, traffic, springs under tension, power tools.',
          'Assess risks — likelihood against consequence, using the risk matrix in DL-RISK-001.',
          'Control risks — applying the hierarchy of control: eliminate, substitute, isolate, engineering, administration, PPE.',
          'Review controls — confirm the controls remain effective and revise where they are not.',
        ],
      },
      { kind: 'heading', number: '05', title: 'Key Hazards and Controls' },
      {
        kind: 'table',
        head: ['Hazard', 'Risk', 'Control measures'],
        rows: [
          ['Manual handling', 'Sprain and strain injuries', 'Team lifts, mechanical aids, training'],
          ['Electrical work', 'Electric shock, arc flash', 'Isolation, lock-out / tag-out, insulated tools'],
          ['Power tools', 'Cuts, sparks, eye injury', 'Inspect tools before use, PPE, correct technique'],
          [
            'Springs under tension',
            'Severe injury from sudden release',
            'Qualified technicians only, correct winding bars',
          ],
          ['Traffic and public', 'Collision, injury to public', 'Cones, barriers, spotter, signage'],
          [
            'Working at heights',
            'Falls from ladders and platforms',
            'Stable ladders, three points of contact, edge protection',
          ],
        ],
      },
      { kind: 'heading', number: '06', title: 'Training and Competency' },
      {
        kind: 'para',
        text: 'Record the minimum training every technician must hold before attending site. Add or remove items to match the work your business actually performs.',
      },
      {
        kind: 'table',
        head: ['Training / competency', 'Required for', 'Evidence held', 'Expiry'],
        rows: [
          ['Construction induction card (White Card)', '', '', ''],
          ['Manual handling', '', '', ''],
          ['Electrical safety awareness and lock-out / tag-out', '', '', ''],
          ['Working at heights and ladder use', '', '', ''],
          ['Elevated work platform / scissor lift (specify class)', '', '', ''],
          ['Product and motor training (specify manufacturers)', '', '', ''],
          ['Emergency procedures and first aid awareness', '', '', ''],
          ['Other (specify)', '', '', ''],
        ],
      },
      { kind: 'heading', number: '07', title: 'Safe Work Procedures' },
      {
        kind: 'table',
        head: ['Stage', 'Procedure'],
        rows: [
          ['Arrival', 'Sign in, identify hazards, establish exclusion zones.'],
          ['Setup', 'Place cones and barriers, isolate power.'],
          ['Removal', 'Disconnect motor, release spring tension safely, remove parts.'],
          ['Installation', 'Install tracks, drums, panels, motors and wiring.'],
          [
            'Testing',
            "Check limits, force settings and safety beams; run the manufacturer's recommended number of full cycles.",
          ],
          ['Completion', 'Clean the site, provide handover instructions, explain warranty.'],
        ],
      },
      {
        kind: 'important',
        title: 'Confirm against the manual',
        text: "Testing cycle counts, force settings and commissioning steps vary between manufacturers. Confirm against the manufacturer's installation instructions for the specific product before relying on this table.",
      },
      { kind: 'heading', number: '08', title: 'Emergency Response' },
      {
        kind: 'bullets',
        items: [
          'Stop work immediately.',
          'Make the area safe — isolate power, block access.',
          'Administer first aid within the limits of your training.',
          'Call 000 for ambulance, fire or police.',
          'Notify management immediately.',
          'Document the incident using DL-INC-001.',
        ],
      },
      { kind: 'heading', number: '09', title: 'Sign Off' },
      { kind: 'signature', parties: ['Worker', 'Supervisor'] },
    ],
  },

  'DL-WHS-003': {
    code: 'DL-WHS-003',
    intro:
      'This statement records how WHS responsibilities are communicated across the business. Clients and principal contractors frequently request it as part of prequalification.',
    blocks: [
      { kind: 'heading', number: '01', title: 'Business Details' },
      { kind: 'businessDetails' },
      { kind: 'documentControl' },
      { kind: 'heading', number: '02', title: 'Statement of Compliance' },
      {
        kind: 'para',
        text: 'The business formally communicates and documents all health and safety responsibilities to employees and subcontractors in accordance with the WHS Act 2011 and the WHS Regulation 2017 applicable in the jurisdiction recorded in Section 01. Every worker is made aware of their role in maintaining a safe workplace, and is provided with the documentation, training and supervision needed to support it.',
      },
      { kind: 'heading', number: '03', title: 'How Responsibilities Are Communicated' },
      { kind: 'para', text: '1. Documented safety procedures' },
      {
        kind: 'bullets',
        items: [
          'Safety responsibilities are defined in Safe Work Method Statements, the Health & Safety Management Plan, and company safety procedures.',
          'Responsibilities include hazard reporting, PPE requirements, safe work practices and incident response.',
        ],
      },
      { kind: 'para', text: '2. Position descriptions containing WHS duties' },
      {
        kind: 'bullets',
        items: [
          'Each role within the business includes specific WHS responsibilities.',
          'Technicians, installers, supervisors and subcontractors are given clear expectations around safety compliance, hazard control and reporting obligations.',
        ],
      },
      { kind: 'para', text: '3. Communication during inductions and training' },
      {
        kind: 'bullets',
        items: [
          'All workers and subcontractors complete a mandatory WHS induction before beginning work.',
          'The induction covers legal obligations, company rules, reporting procedures, emergency processes and safe work responsibilities.',
        ],
      },
      { kind: 'para', text: '4. Ongoing toolbox talks and safety meetings' },
      {
        kind: 'bullets',
        items: [
          'WHS responsibilities are reinforced through toolbox meetings, site briefings and regular safety discussions.',
          'Changes to legislation, procedures or safety requirements are communicated promptly.',
        ],
      },
      { kind: 'para', text: '5. Performance reviews and safety targets' },
      {
        kind: 'bullets',
        items: [
          'Safety performance is included in employee expectations and reviewed during performance discussions.',
          'Workers are measured on safe behaviour, compliance with PPE and procedures, and their contribution to a hazard-free workplace.',
        ],
      },
      { kind: 'para', text: '6. Accessible WHS documentation' },
      {
        kind: 'bullets',
        items: [
          'Safety documents, policies and procedures are stored so that staff and subcontractors can access them.',
          'Workers acknowledge receipt and understanding of updated WHS responsibilities.',
        ],
      },
      { kind: 'heading', number: '04', title: 'Acknowledgement Record' },
      {
        kind: 'blankRows',
        head: ['Name', 'Position', 'Document issued', 'Date', 'Signature'],
        count: 10,
      },
      { kind: 'heading', number: '05', title: 'Approval' },
      { kind: 'signature', parties: ['Director / responsible officer'] },
    ],
  },

  'DL-WHS-004': {
    code: 'DL-WHS-004',
    intro:
      'Use this statement to show how the business keeps up with legislative change and feeds it back into day-to-day work procedures.',
    blocks: [
      { kind: 'heading', number: '01', title: 'Business Details' },
      { kind: 'businessDetails' },
      { kind: 'documentControl' },
      { kind: 'heading', number: '02', title: 'Keeping Up To Date With WHS Legislation' },
      {
        kind: 'para',
        text: 'The business maintains an active commitment to staying informed of changes relating to:',
      },
      {
        kind: 'bullets',
        items: [
          'The WHS Act 2011 and WHS Regulation 2017 applicable in our jurisdiction',
          'SafeWork alerts, updates and industry bulletins',
          'Relevant Australian Standards (AS/NZS) covering doors, gates, electrical safety and machinery',
          'Industry best practice and manufacturer technical updates for the product ranges we install and service',
        ],
      },
      {
        kind: 'para',
        text: 'Updates are monitored through the WHS regulator, Standards Australia, manufacturer notices and industry associations.',
      },
      {
        kind: 'important',
        title: 'Complete before issuing',
        text: 'List the specific manufacturers your business is authorised for in the field below, rather than naming brands you do not hold training or accreditation for.',
      },
      {
        kind: 'fields',
        rows: [
          { label: 'Manufacturers / product ranges serviced by this business', value: null },
          { label: 'Industry associations and subscriptions held', value: null },
        ],
      },
      { kind: 'heading', number: '03', title: 'Updating Work Procedures and Practices' },
      {
        kind: 'para',
        text: 'Legislative changes are reviewed and incorporated into company practice through:',
      },
      {
        kind: 'bullets',
        items: [
          'Updates to Safe Work Method Statements',
          'Revision of the Health & Safety Management Plan',
          'Toolbox talks and internal briefings',
          'Updated installation, servicing and repair procedures',
          'Continuous improvement meetings and safety reviews',
        ],
      },
      { kind: 'heading', number: '04', title: 'Review Log' },
      {
        kind: 'blankRows',
        head: ['Date', 'Change identified', 'Source', 'Documents updated', 'Completed by'],
        count: 8,
      },
      { kind: 'heading', number: '05', title: 'Commitment Statement' },
      {
        kind: 'para',
        text: 'The business is committed to maintaining high WHS standards by continuously monitoring, reviewing and integrating legislative and industry-specific changes into daily operations.',
      },
      { kind: 'signature', parties: ['Director / responsible officer'] },
    ],
  },

  'DL-WHS-005': {
    code: 'DL-WHS-005',
    intro:
      'Deliver this induction to every worker and subcontractor before they start. The record at the back is the evidence that it happened.',
    blocks: [
      { kind: 'heading', number: '01', title: 'Business Details' },
      { kind: 'businessDetails' },
      { kind: 'documentControl' },
      { kind: 'heading', number: '02', title: 'Induction Compliance Statement' },
      {
        kind: 'para',
        text: 'The business requires all workers and subcontractors to complete a formal safety induction prior to commencing any work. The induction is aligned with the WHS Act 2011 and WHS Regulation 2017 applicable in the jurisdiction recorded in Section 01.',
      },
      { kind: 'heading', number: '03', title: 'Rights and Responsibilities' },
      { kind: 'para', text: 'All inducted workers are informed of:' },
      {
        kind: 'bullets',
        items: [
          'Their WHS rights, including the right to cease unsafe work.',
          'Their responsibility to follow safety procedures, SWMS and instructions.',
          'The requirement to report hazards, incidents and near misses.',
          'PPE obligations and maintaining safe behaviour on all worksites.',
        ],
      },
      { kind: 'heading', number: '04', title: 'Workplace Hazards Covered' },
      {
        kind: 'bullets',
        items: [
          'Manual handling of motors, shutters, doors and heavy components.',
          'Electrical hazards and lock-out / tag-out procedures.',
          'Working at heights, ladder use and fall prevention.',
          'Power tool safety, metal cutting, grinding and sharp edges.',
          'High-tension springs in garage doors and shutters.',
          'Traffic and public risk on residential and commercial sites.',
        ],
      },
      { kind: 'heading', number: '05', title: 'Safe Work Procedures Covered' },
      {
        kind: 'bullets',
        items: [
          'Safe Work Method Statements.',
          'Site pre-start hazard assessments.',
          'Isolation and tagging procedures.',
          'Correct installation, servicing and repair processes.',
          'Emergency procedures and communication protocols.',
        ],
      },
      {
        kind: 'important',
        text: 'No worker or subcontractor is permitted to begin work until they have completed the induction covering every item listed above.',
      },
      { kind: 'heading', number: '06', title: 'Induction Record' },
      {
        kind: 'fields',
        rows: [
          { label: 'Worker / subcontractor name', value: null },
          { label: 'Position', value: null },
          { label: 'Employee / contractor (circle one)', value: null },
          { label: 'Company', value: null },
          { label: 'Date of induction', value: null },
          { label: 'Inducted by', value: null },
          { label: 'Position', value: null },
        ],
      },
      {
        kind: 'checkboxes',
        lead: 'Tick to confirm each item was covered and understood:',
        items: [
          'WHS rights and duties',
          'Right to cease unsafe work',
          'Hazard and incident reporting',
          'PPE requirements',
          'Manual handling',
          'Electrical safety and LOTO',
          'Working at heights',
          'Springs under tension',
          'Power tool safety',
          'Traffic and public control',
          'SWMS for the task',
          'Emergency procedures',
        ],
      },
      { kind: 'fields', rows: [{ label: 'Additional site-specific matters covered', value: null }] },
      {
        kind: 'para',
        text: 'I confirm that I have received and understood this induction, that I have had the opportunity to ask questions, and that I will not undertake any task I have not been trained and authorised to perform.',
      },
      { kind: 'signature', parties: ['Worker / subcontractor', 'Inducted by'] },
    ],
  },

  'DL-WHS-006': {
    code: 'DL-WHS-006',
    intro:
      'This policy covers fitness for duty, testing and fatigue management. Testing arrangements carry privacy and employment-law obligations, so review the highlighted items before issuing it.',
    blocks: [
      { kind: 'heading', number: '01', title: 'Business Details' },
      { kind: 'businessDetails' },
      { kind: 'documentControl' },
      { kind: 'heading', number: '02', title: 'Drug and Alcohol Policy' },
      {
        kind: 'para',
        text: "The business is committed to ensuring all workers are fit for duty and capable of performing work safely. This policy supports the business's duties under the WHS Act 2011 and WHS Regulation 2017. The following is strictly prohibited:",
      },
      {
        kind: 'bullets',
        items: [
          'Use or possession of illegal drugs on any company or client site.',
          'Reporting to work under the influence of drugs or alcohol.',
          'Misuse of prescription medication that impairs judgement or safety.',
        ],
      },
      { kind: 'para', text: 'Worker responsibilities' },
      {
        kind: 'bullets',
        items: [
          'Present to work fit for duty.',
          'Report any medication that may affect performance.',
          'Comply with testing requirements.',
        ],
      },
      { kind: 'para', text: 'Company responsibilities' },
      {
        kind: 'bullets',
        items: [
          'Provide a safe workplace free from impairment risks.',
          'Manage impaired workers safely and respectfully.',
          'Apply disciplinary processes fairly and consistently.',
        ],
      },
      { kind: 'heading', number: '03', title: 'Testing Program' },
      {
        kind: 'para',
        text: 'Complete the fields below to record the testing arrangements that apply in your business. Leave blank any element you do not operate.',
      },
      {
        kind: 'fields',
        rows: [
          { label: 'Testing provider', value: null },
          { label: 'Minimum testing frequency', value: null },
          { label: 'Circumstances triggering a test', value: null },
          { label: 'Who may authorise a test', value: null },
          { label: 'Where results are stored', value: null },
        ],
      },
      {
        kind: 'important',
        title: 'Review before use',
        text: "Drug and alcohol testing involves the collection of sensitive health information and interacts with privacy law, the Fair Work Act, any applicable modern award or enterprise agreement, and the terms of each worker's engagement. Confirm your testing program, consent arrangements and consequences of a positive or refused test with a qualified employment adviser before implementing this section.",
      },
      { kind: 'heading', number: '04', title: 'Fatigue Management and Rest Scheduling' },
      {
        kind: 'para',
        text: 'Work scheduling practices must support adequate rest and prevent worker fatigue. Record the limits that apply in your business:',
      },
      {
        kind: 'table',
        head: ['Scheduling control', 'Limit set by this business'],
        rows: [
          ['Maximum shift length (including travel)', ''],
          ['Minimum rest between shifts', ''],
          ['Mandatory break frequency and duration', ''],
          ['Maximum consecutive days worked', ''],
          ['Driving or operating machinery when fatigued', 'Not permitted'],
        ],
      },
      { kind: 'para', text: 'High-risk fatigue situations' },
      {
        kind: 'bullets',
        items: [
          'Emergency call-outs at night.',
          'Extended repair works causing overtime.',
          'Long-distance travel to remote job sites.',
        ],
      },
      { kind: 'para', text: 'Control measures' },
      {
        kind: 'bullets',
        items: [
          'Shift rotation to avoid excessive hours.',
          'Supervisor monitoring of fatigue indicators.',
          'Workers required to report fatigue immediately.',
        ],
      },
      { kind: 'heading', number: '05', title: 'Rest and Break Log' },
      {
        kind: 'blankRows',
        head: [
          'Date',
          'Shift start',
          'Shift end',
          'Total hours',
          'Breaks taken',
          'Worker signature',
          'Supervisor',
        ],
        count: 8,
      },
      { kind: 'heading', number: '06', title: 'Policy Sign Off' },
      {
        kind: 'para',
        text: 'I have read and understood this policy, including the fitness for duty requirements and the fatigue management limits recorded above.',
      },
      { kind: 'signature', parties: ['Worker', 'Director / responsible officer'] },
    ],
  },

  'DL-WHS-007': {
    code: 'DL-WHS-007',
    intro:
      'Vehicles are the mobile workplace in this industry. This policy sets the first aid kit requirement and provides the weekly compliance log.',
    blocks: [
      { kind: 'heading', number: '01', title: 'Business Details' },
      { kind: 'businessDetails' },
      { kind: 'documentControl' },
      { kind: 'heading', number: '02', title: 'Purpose' },
      {
        kind: 'para',
        text: "This policy ensures that all company vehicles, including any subcontractor vehicles working under the business, are equipped with a compliant and fully stocked first aid kit at all times. It supports the business's duties under the WHS Act 2011 and WHS Regulation 2017.",
      },
      { kind: 'heading', number: '03', title: 'Policy Requirements' },
      {
        kind: 'bullets',
        items: [
          'Every company vehicle must contain a complete, accessible and in-date first aid kit.',
          'Every subcontractor vehicle operating under the business must also carry a compliant first aid kit.',
          'Kits must include adequate supplies for the hazards of this work, including electrical injury, cuts, abrasions and emergency response situations.',
        ],
      },
      {
        kind: 'important',
        title: 'Confirm your kit requirement',
        text: 'First aid kit contents and the number of kits required depend on the size of the workforce, the nature of the work and the distance from emergency services. Confirm your requirement against the First Aid in the Workplace Code of Practice published by your WHS regulator.',
      },
      { kind: 'heading', number: '04', title: 'Driver Responsibility' },
      { kind: 'para', text: 'The designated driver of each vehicle is responsible for:' },
      {
        kind: 'bullets',
        items: [
          'Checking the first aid kit before starting work each day.',
          'Ensuring all items are stocked and not expired.',
          'Reporting missing or damaged items immediately.',
          'Signing the weekly compliance log.',
        ],
      },
      { kind: 'heading', number: '05', title: 'Management Responsibility' },
      {
        kind: 'bullets',
        items: [
          'Conduct regular inspections of all worker and subcontractor vehicles.',
          'Verify first aid kit condition and replenishment.',
          'Record findings in the inspection register below.',
          'Enforce corrective actions where required.',
        ],
      },
      { kind: 'heading', number: '06', title: 'Weekly First Aid Kit Compliance Log' },
      {
        kind: 'blankRows',
        head: [
          'Week ending',
          'Driver',
          'Vehicle rego',
          'Kit complete',
          'Items replaced',
          'Driver sign',
          'Reviewed by',
        ],
        count: 10,
      },
      { kind: 'signature', parties: ['Director / responsible officer'] },
    ],
  },

  'DL-RISK-001': {
    code: 'DL-RISK-001',
    intro:
      'A risk register lists the hazards your work creates every day. The assessment form behind it is completed on site, before work starts, whenever conditions differ from the register.',
    blocks: [
      { kind: 'heading', number: '01', title: 'Business Details' },
      { kind: 'businessDetails' },
      { kind: 'documentControl' },
      { kind: 'heading', number: '02', title: 'How To Use This Document' },
      {
        kind: 'bullets',
        items: [
          'Review the register below and delete any hazard your business does not encounter.',
          'Add hazards specific to your equipment, sites and workforce.',
          'Confirm the controls listed are the controls you actually use — a control you do not apply must not remain in the register.',
          'Complete a site risk assessment (Section 05) before work begins on any job where conditions differ from the register.',
        ],
      },
      { kind: 'heading', number: '03', title: 'Risk Register' },
      {
        kind: 'para',
        text: 'Common hazards associated with installation, repair, servicing and emergency work for garage doors, roller shutters, sliding gates, swing gates and their electrical components.',
      },
      {
        kind: 'table',
        head: ['Hazard', 'Risk description', 'Initial risk', 'Control measures'],
        rows: [
          [
            'Manual handling',
            'Strain and back injury lifting motors and doors',
            'Medium',
            'Team lifts, trolleys and mechanical aids, correct technique',
          ],
          [
            'Electrical work',
            'Electric shock, arc flash',
            'High',
            'Isolation, lock-out / tag-out, insulated tools, licensed electrician',
          ],
          [
            'Power tools',
            'Cuts, sparks, eye injury',
            'Medium',
            'PPE, tool inspection and test tagging, correct use',
          ],
          [
            'Springs under tension',
            'Severe injury from sudden release of tension',
            'High',
            'Qualified technicians only, correct winding bars, no adjustment without rated PPE',
          ],
          [
            'Working at heights',
            'Falls from ladders and platforms',
            'High',
            'Stable ladder, three points of contact, EWP where practicable',
          ],
          [
            'Traffic and vehicles',
            'Collision risk around work areas',
            'Medium',
            'Cones, barricades, spotter, high-visibility clothing',
          ],
        ],
      },
      {
        kind: 'important',
        title: 'Ratings must be confirmed on site',
        text: 'The ratings above are indicative starting points carried over from common industry practice. Risk depends on the site, the equipment and the people doing the work — confirm the rating on site rather than relying on the register alone.',
      },
      { kind: 'heading', number: '04', title: 'Risk Matrix' },
      {
        kind: 'para',
        text: 'Step 1 — consider how likely the risk is to be encountered and what might happen. Step 2 — use the matrix to determine the likely risk level. Step 3 — identify and apply control measures using the hierarchy of control.',
      },
      {
        kind: 'table',
        head: [
          '',
          'Consequence',
          'Almost certain (A)',
          'Likely (B)',
          'Possible (C)',
          'Unlikely (D)',
          'Rare (E)',
        ],
        rows: [
          [
            '1',
            'Catastrophic — fatality or permanent disability; toxic release of chemicals; long-term or irreversible environmental impact; loss of facilities; very high financial loss',
            'E (25)',
            'E (24)',
            'E (22)',
            'E (19)',
            'H (15)',
          ],
          [
            '2',
            'Major — long-term illness or serious injury; serious but reversible environmental impact; major property damage; loss of production; high financial loss',
            'E (23)',
            'E (21)',
            'E (18)',
            'H (14)',
            'M (10)',
          ],
          [
            '3',
            'Moderate — medical treatment requiring up to several days off work; reversible environmental impact; significant property damage; medium to high financial loss',
            'E (20)',
            'H (17)',
            'H (13)',
            'M (9)',
            'M (6)',
          ],
          [
            '4',
            'Minor — minor injury requiring first aid; minor reversible environmental impact; moderate property damage; low to medium financial loss',
            'H (16)',
            'H (12)',
            'M (8)',
            'L (5)',
            'L (3)',
          ],
          [
            '5',
            'Insignificant — no injuries or first aid only; minor property damage or environmental nuisance; very low financial loss',
            'M (11)',
            'M (7)',
            'L (4)',
            'L (2)',
            'L (1)',
          ],
        ],
      },
      {
        kind: 'table',
        head: ['Likelihood', 'Meaning'],
        rows: [
          ['A — Almost certain', 'Event is expected to occur in most circumstances'],
          ['B — Likely', 'Event will probably occur in most circumstances'],
          ['C — Possible', 'Event might occur at some time'],
          ['D — Unlikely', 'Event could occur at some time'],
          ['E — Rare', 'Event may occur only in exceptional circumstances'],
        ],
      },
      {
        kind: 'table',
        head: ['Risk level', 'Action required'],
        rows: [
          ['E — Extreme', 'Urgent. Immediate action required to control the risk.'],
          ['H — High', 'Highest management decision required urgently.'],
          ['M — Medium', 'Follow management instructions regarding the risk.'],
          ['L — Low', 'May not require immediate attention — monitor.'],
        ],
      },
      {
        kind: 'table',
        head: ['Hierarchy of control', '', ''],
        rows: [
          ['1. Elimination', '2. Substitution', '3. Isolation'],
          ['4. Engineering', '5. Administration', '6. PPE'],
        ],
      },
      { kind: 'para', text: 'Highest protection at 1, lowest at 6. Always work down the list, not up it.' },
      { kind: 'heading', number: '05', title: 'Site Risk Assessment' },
      {
        kind: 'para',
        text: 'Complete before work begins. One form per task or per significant change in conditions.',
      },
      {
        kind: 'fields',
        rows: [
          { label: 'Site / job number', value: null },
          { label: 'Date', value: null },
          { label: 'Task being assessed', value: null },
          { label: 'Assessed by', value: null },
          { label: 'Position', value: null },
        ],
      },
      {
        kind: 'blankRows',
        head: [
          'Hazard identified',
          'Potential harm',
          'L',
          'C',
          'Rating',
          'Controls required',
          'Person responsible',
          'Date',
        ],
        count: 8,
      },
      { kind: 'fields', rows: [{ label: 'Newly identified hazards and additional controls', value: null }] },
      { kind: 'signature', parties: ['Assessed by', 'Supervisor approval'] },
    ],
  },

  'DL-INSP-001': {
    code: 'DL-INSP-001',
    intro:
      "Complete one checklist per asset per attendance. The record it produces is what supports a warranty claim, a defect quotation, or a client's asset register.",
    blocks: [
      { kind: 'heading', number: '01', title: 'Job and Asset Details' },
      {
        kind: 'fields',
        rows: [
          { label: 'Client name', value: null },
          { label: 'Asset ID / tag', value: null },
          { label: 'Site address', value: null },
          { label: 'Technician', value: null },
          { label: 'Service date', value: null },
          { label: 'Meter / cycles', value: null },
          { label: 'Job / work order number', value: null },
          { label: 'Licence or qualification held', value: null },
        ],
      },
      {
        kind: 'checkboxes',
        lead: 'Asset type',
        items: [
          'Roller shutter',
          'Sliding gate',
          'Swing gate',
          'Sectional door',
          'Tilt / up-and-over door',
          'Industrial shutter',
          'Automatic door',
          'Other (specify)',
        ],
      },
      {
        kind: 'checkboxes',
        lead: 'Service type',
        items: ['Routine (6 monthly)', 'Routine (12 monthly)', 'Corrective', 'Breakdown / call-out'],
      },
      { kind: 'heading', number: '02', title: 'General Mechanical and Structural Integrity' },
      {
        kind: 'table',
        head: ['Inspection item', 'Specification & standard', 'Pass / fail / N/A'],
        rows: [
          [
            'Structural framing and guides',
            'Check vertical guides, wall angles, track alignments and structural mounting brackets for loose anchor bolts, cracking, corrosion or distortion.',
            'P    F    N/A',
          ],
          [
            'Curtain, door leaves and gate panels',
            'Inspect slats, panels, infills, hinges, welds and fixings for impact damage, corrosion, missing end locks or binding during travel.',
            'P    F    N/A',
          ],
          [
            'Counterbalance and torsion springs',
            'Inspect spring tension, winding cones and anchor plugs; check for fatigue, elongation or rust pitting. Do not adjust without rated PPE and correct winding bars.',
            'P    F    N/A',
          ],
          [
            'Drums, shafts, bearings and pulleys',
            'Verify bearing alignment, lubrication status, pillow block bolts and cable drums, and confirm components are secured to the main drive shaft.',
            'P    F    N/A',
          ],
          [
            'Gate track, rollers and guide rollers',
            'Check sliding or cantilever gate track for debris, levelness, wheel wear, bearing play and smooth upper guide roller operation.',
            'P    F    N/A',
          ],
        ],
      },
      { kind: 'heading', number: '03', title: 'Drive System, Gearbox and Transmission' },
      {
        kind: 'table',
        head: ['Inspection item', 'Specification & standard', 'Pass / fail / N/A'],
        rows: [
          [
            'Operator motor and gearbox unit',
            'Check for abnormal motor noise, vibration, overheating, oil leaks in industrial gearboxes, and secure mounting foot bolts.',
            'P    F    N/A',
          ],
          [
            'Drive chain, belts and sprockets',
            'Inspect chain tension, alignment, wear on sprocket teeth and master links; apply the appropriate industrial lubricant.',
            'P    F    N/A',
          ],
          [
            'Clutch and manual release mechanism',
            'Test the manual hand chain or quick-release disconnect. Verify the clutch re-engages securely and the manual release operates correctly.',
            'P    F    N/A',
          ],
          [
            'Limit switches (mechanical / electronic)',
            'Verify precise open and close limit settings. Ensure cams, microswitches or absolute encoders do not slip during cycles.',
            'P    F    N/A',
          ],
        ],
      },
      { kind: 'heading', number: '04', title: 'Electrical, Safety and Control Systems' },
      {
        kind: 'table',
        head: ['Inspection item', 'Specification & standard', 'Pass / fail / N/A'],
        rows: [
          [
            'Control panel and enclosure',
            'Inspect cabinet seals, door locks, internal wiring terminations, fuses, circuit breakers, isolators and transformer voltage outputs.',
            'P    F    N/A',
          ],
          [
            'Photoelectric beams and safety sensors',
            'Test alignment, clean lenses, and verify obstruction reversal response on photoelectric beams and light curtains.',
            'P    F    N/A',
          ],
          [
            'Safety edge and pneumatic / resistive ribs',
            'Test bottom bar safety edge sensitivity, wireless transmitter and receiver battery state, and automatic reversal on contact.',
            'P    F    N/A',
          ],
          [
            'Access control and interlock integration',
            'Test loop detectors, intercoms, access card readers, keypads, radar sensors, fire alarm relays and warning lights.',
            'P    F    N/A',
          ],
          [
            'Emergency stop and interlock switchgear',
            'Verify operation of all emergency-stop buttons, safety pull cords and interlocking door sequences.',
            'P    F    N/A',
          ],
        ],
      },
      { kind: 'heading', number: '05', title: 'Lubrication and Operational Cycle Testing' },
      {
        kind: 'table',
        head: ['Inspection item', 'Specification & standard', 'Pass / fail / N/A'],
        rows: [
          [
            'Lubrication of moving parts',
            'Apply suitable grease or oil to chains, bearings, hinges, guide tracks where specified, spring coils and sliding gate tracks.',
            'P    F    N/A',
          ],
          [
            'Full cycle operational test',
            "Execute the manufacturer's recommended number of full open and close cycles under power. Monitor current draw, motor temperature rise, noise and smoothness.",
            'P    F    N/A',
          ],
          [
            'Final operational result',
            'Confirm the asset opens, closes, stops and reverses correctly. Record any defects requiring repair, replacement or further quotation.',
            'P    F    N/A',
          ],
        ],
      },
      { kind: 'heading', number: '06', title: 'Technician Observations, Defects and Recommendations' },
      { kind: 'fields', rows: [{ label: 'Observations', value: null }] },
      {
        kind: 'checkboxes',
        lead: 'Recommended follow-up',
        items: [
          'No further action required',
          'Repairs recommended',
          'Replacement / upgrade recommended',
          'Quotation to follow',
        ],
      },
      { kind: 'heading', number: '07', title: 'Photographic Record' },
      {
        kind: 'blankRows',
        head: ['Photo ref', 'Caption', 'Location on asset', 'Date'],
        count: 6,
      },
      {
        kind: 'para',
        text: 'Attach photographs to the job record. Do not include images that identify third parties without their consent.',
      },
      { kind: 'heading', number: '08', title: 'Service Sign-Off and Acceptance' },
      { kind: 'signature', parties: ['Technician', 'Client representative'] },
    ],
  },

  'DL-INC-001': {
    code: 'DL-INC-001',
    intro:
      'Use this form for injuries, near misses, hazards and property damage. Complete it as soon as the area is safe and the injured person has been cared for.',
    blocks: [
      { kind: 'heading', number: '01', title: 'Business Details' },
      { kind: 'businessDetails' },
      { kind: 'documentControl' },
      {
        kind: 'important',
        title: 'Notifiable incidents',
        text: 'Serious incidents are notifiable to the WHS regulator, and the incident site generally must not be disturbed until the regulator directs otherwise. Confirm your notification obligations before altering the scene.',
      },
      { kind: 'heading', number: '02', title: 'Report Type' },
      {
        kind: 'checkboxes',
        items: [
          'Injury',
          'Near miss',
          'Hazard report',
          'Property damage',
          'Environmental',
          'Public / third party',
        ],
      },
      { kind: 'heading', number: '03', title: 'Incident Information' },
      {
        kind: 'fields',
        rows: [
          { label: 'Date of incident', value: null },
          { label: 'Time of incident', value: null },
          { label: 'Location of incident', value: null },
          { label: 'Site / job number', value: null },
          { label: 'Client', value: null },
          { label: 'Reported to (name and time)', value: null },
        ],
      },
      { kind: 'heading', number: '04', title: 'People Involved' },
      {
        kind: 'blankRows',
        head: ['Name', 'Role (worker / contractor / public)', 'Contact number', 'Involvement'],
        count: 5,
      },
      {
        kind: 'blankRows',
        head: ['Witness name', 'Contact number', 'Statement taken'],
        count: 3,
      },
      { kind: 'heading', number: '05', title: 'Description of the Incident' },
      {
        kind: 'para',
        text: 'Describe what happened, including the sequence of events leading up to the incident.',
      },
      { kind: 'fields', rows: [{ label: 'Description', value: null }] },
      { kind: 'heading', number: '06', title: 'Injury or Damage Details' },
      {
        kind: 'fields',
        rows: [
          { label: 'Details of injury or damage', value: null },
          { label: 'Body part affected (if injury)', value: null },
          { label: 'First aid given (yes / no)', value: null },
          { label: 'Name of first aider', value: null },
          { label: 'Medical treatment sought', value: null },
          { label: 'Time lost from work', value: null },
        ],
      },
      { kind: 'heading', number: '07', title: 'Immediate Actions Taken' },
      { kind: 'fields', rows: [{ label: 'Immediate actions', value: null }] },
      { kind: 'heading', number: '08', title: 'Contributing Factors' },
      {
        kind: 'checkboxes',
        items: [
          'Procedure not followed',
          'PPE not worn or unavailable',
          'Equipment fault or failure',
          'Inadequate training',
          'Site conditions',
          'Fatigue',
          'Communication breakdown',
          'Third party action',
          'Other (describe below)',
        ],
      },
      { kind: 'heading', number: '09', title: 'Corrective Actions To Prevent Recurrence' },
      {
        kind: 'blankRows',
        head: ['Corrective action', 'Responsible person', 'Due date', 'Completed'],
        count: 5,
      },
      { kind: 'heading', number: '10', title: 'Documents Updated As a Result' },
      {
        kind: 'checkboxes',
        items: [
          'SWMS',
          'Risk register',
          'HSMP',
          'Induction content',
          'Toolbox talk delivered',
          'No change required',
        ],
      },
      { kind: 'heading', number: '11', title: 'Sign Off' },
      { kind: 'signature', parties: ['Reported by', 'Supervisor / manager'] },
    ],
  },

  'DL-EMG-001': {
    code: 'DL-EMG-001',
    intro:
      'This plan covers two things: keeping people safe when something goes wrong, and keeping the business running afterwards. Complete the contact tree before it is needed.',
    blocks: [
      { kind: 'heading', number: '01', title: 'Business Details' },
      { kind: 'businessDetails' },
      { kind: 'documentControl' },
      { kind: 'heading', number: '02', title: 'Emergency Contacts' },
      {
        kind: 'table',
        head: ['Role', 'Name', 'Phone', 'Alternate'],
        rows: [
          ['Emergency services', 'Ambulance / Fire / Police', '000', ''],
          ['Director / responsible officer', '', '', ''],
          ['Supervisor', '', '', ''],
          ['Nominated first aid officer', '', '', ''],
          ['Electricity supply authority', '', '', ''],
          ['WHS regulator', '', '', ''],
          ['Insurer — claims line', '', '', ''],
        ],
      },
      { kind: 'heading', number: '03', title: 'Business Continuity Plan' },
      {
        kind: 'para',
        text: 'This plan supports continued operation during disruption while keeping staff and clients safe.',
      },
      { kind: 'para', text: 'Objectives' },
      {
        kind: 'bullets',
        items: [
          'Maintain emergency response and essential services.',
          'Protect worker safety and communication.',
          'Reduce downtime and restore operations quickly.',
        ],
      },
      { kind: 'para', text: 'Disruptions covered' },
      {
        kind: 'para',
        text: 'Power loss, equipment failure, supply delays, extreme weather, worker shortages.',
      },
      { kind: 'para', text: 'Continuity actions' },
      {
        kind: 'bullets',
        items: [
          'Backup communication arrangements.',
          'Spare parts stock for common failures.',
          'Multiple suppliers for critical components.',
          'Cross-trained technicians.',
          'Emergency contact tree kept current.',
        ],
      },
      { kind: 'heading', number: '04', title: 'Emergency Response Plan' },
      { kind: 'para', text: 'Emergency types' },
      {
        kind: 'para',
        text: 'Injury, electrical incident, fire, motor failure trapping vehicles or people, structural failure, traffic collision.',
      },
      {
        kind: 'table',
        head: ['Role', 'Responsibility in an emergency'],
        rows: [
          ['Supervisor', 'Coordinates the response and contacts emergency services.'],
          ['Lead technician', 'Isolates hazards and supports injured workers.'],
          ['Workers', 'Follow directions and assist as required.'],
        ],
      },
      { kind: 'heading', number: '05', title: 'Emergency Response Procedure' },
      {
        kind: 'bullets',
        items: [
          'Stop work immediately.',
          'Make the area safe — isolate power, block access.',
          'Administer first aid within the limits of your training until help arrives.',
          'Call 000 for ambulance, fire or police.',
          'Notify management immediately.',
          'Document the incident using DL-INC-001, and preserve the site if the incident is notifiable.',
        ],
      },
      { kind: 'heading', number: '06', title: 'Emergency Training and Drills' },
      { kind: 'para', text: 'Training includes' },
      {
        kind: 'bullets',
        items: [
          'Emergency communication',
          'First aid awareness',
          'Fire extinguisher basics',
          'Electrical isolation (lock-out / tag-out)',
          'Manual handling',
        ],
      },
      { kind: 'para', text: 'Drill schedule' },
      {
        kind: 'table',
        head: ['Activity', 'Frequency set by this business', 'Last completed', 'Next due'],
        rows: [
          ['Toolbox talks', '', '', ''],
          ['Emergency drill', '', '', ''],
          ['Induction refresher', '', '', ''],
          ['First aid kit audit', '', '', ''],
        ],
      },
      {
        kind: 'para',
        text: 'All training is documented and retained as required by the WHS Regulation.',
      },
      { kind: 'heading', number: '07', title: 'Site-Specific Emergency Arrangements' },
      {
        kind: 'fields',
        rows: [
          { label: 'Muster point', value: null },
          { label: 'Nearest hospital', value: null },
          { label: 'Location of first aid kit', value: null },
          { label: 'Location of extinguisher', value: null },
          { label: 'Main electrical isolation point', value: null },
        ],
      },
      { kind: 'heading', number: '08', title: 'Sign Off' },
      { kind: 'signature', parties: ['Director / responsible officer'] },
    ],
  },

  'DL-JOB-001': {
    code: 'DL-JOB-001',
    intro:
      'Issue on completion. The certificate records what was installed, what is covered, and for how long — which is what prevents a dispute two years later.',
    blocks: [
      { kind: 'heading', number: '01', title: 'Customer Details' },
      {
        kind: 'fields',
        rows: [
          { label: 'Customer', value: null },
          { label: 'Site contact', value: null },
          { label: 'Site address', value: null },
          { label: 'Contract / job number', value: null },
          { label: 'Date of installation', value: null },
        ],
      },
      { kind: 'heading', number: '02', title: 'Works Completed' },
      {
        kind: 'para',
        text: 'List each item of work and equipment supplied. Record model and serial numbers where available — they are what a future technician will need.',
      },
      {
        kind: 'blankRows',
        head: ['Item / equipment', 'Manufacturer & model', 'Serial number', 'Qty'],
        count: 6,
      },
      { kind: 'fields', rows: [{ label: 'Additional works performed', value: null }] },
      { kind: 'heading', number: '03', title: 'Warranty Terms' },
      {
        kind: 'para',
        text: "All products and components supplied and installed by the business are covered by the applicable manufacturer's warranty and by the workmanship warranty stated on this certificate.",
      },
      {
        kind: 'table',
        head: ['Coverage', 'Period', 'Commences', 'Expires'],
        rows: [
          ['Workmanship — installation', '', '', ''],
          ['Motor / operator (manufacturer)', '', '', ''],
          ['Locking system', '', '', ''],
          ['Other equipment (specify)', '', '', ''],
        ],
      },
      { kind: 'para', text: 'Exclusions' },
      {
        kind: 'bullets',
        items: [
          'Impact damage, misuse and third-party interference.',
          'Pre-existing defects in structures, fixings or power supply not installed by us.',
          'Damage caused by failure to carry out the recommended maintenance.',
          'Fair wear and tear on consumable items.',
        ],
      },
      {
        kind: 'important',
        title: 'Consumer law',
        text: 'This warranty is provided in addition to, and does not exclude, restrict or modify, any rights the customer has under the Australian Consumer Law. Confirm your warranty wording against the ACL warranties-against-defects requirements before issuing this certificate to consumers.',
      },
      { kind: 'heading', number: '04', title: 'Maintenance Recommendation' },
      {
        kind: 'para',
        text: 'A regular maintenance contract is strongly recommended to prevent problems, ensure smooth operation and maintain warranty coverage. Record the interval agreed:',
      },
      {
        kind: 'fields',
        rows: [
          { label: 'Recommended service interval', value: null },
          { label: 'First service due', value: null },
          { label: 'Maintenance agreement in place (Y/N)', value: null },
        ],
      },
      { kind: 'heading', number: '05', title: 'Handover' },
      {
        kind: 'checkboxes',
        items: [
          'Operating instructions demonstrated',
          'Manual release demonstrated',
          'Safety reversal tested with customer present',
          'Remotes / handsets issued (record quantity)',
          'Manufacturer documentation handed over',
          'Maintenance requirements explained',
        ],
      },
      { kind: 'heading', number: '06', title: 'Authorisation' },
      { kind: 'signature', parties: ['Issued for the business', 'Received by customer'] },
    ],
  },

  'DL-SWMS-001': {
    code: 'DL-SWMS-001',
    intro:
      'A Safe Work Method Statement is a legal requirement for high-risk construction work. It must be prepared in consultation with the workers who will do the task, kept available on site, and reviewed whenever the method or the conditions change.',
    blocks: [
      { kind: 'heading', number: '01', title: 'SWMS Details' },
      { kind: 'businessDetails' },
      {
        kind: 'fields',
        rows: [
          { label: 'Contact name', value: null },
          { label: 'SWMS number', value: null },
          { label: 'Issue date', value: null },
          { label: 'Review date', value: null },
          { label: 'Person responsible for implementation, monitoring and compliance', value: null },
        ],
      },
      { kind: 'heading', number: '02', title: 'Project Details' },
      {
        kind: 'fields',
        rows: [
          { label: 'Project name', value: null },
          { label: 'Location', value: null },
          { label: 'Principal contractor', value: null },
          { label: 'Site manager', value: null },
          { label: 'Submitted to', value: null },
          { label: 'Submission date', value: null },
          { label: 'Location of first aid kit', value: null },
          { label: 'Muster point', value: null },
        ],
      },
      { kind: 'heading', number: '03', title: 'Worker Consultation and Sign-On' },
      {
        kind: 'para',
        text: 'I acknowledge that I have been trained in this SWMS, that the controls are clearly understood, that my qualifications are current for the activity, and that I will only undertake the work activities prescribed. I have been consulted and had the opportunity to give input into this SWMS.',
      },
      {
        kind: 'blankRows',
        head: ['Name', 'Role', 'Qualifications / licences held', 'Signature', 'Date'],
        count: 8,
      },
      {
        kind: 'para',
        text: 'This SWMS is implemented with all workers inducted into it immediately after the site-specific induction, and monitored by documented task observation at intervals not exceeding three months. Where amendments are made during monitoring and review, all applicable workers are re-inducted into the SWMS.',
      },
      {
        kind: 'blankRows',
        head: ['Review no.', 'Date', 'Reviewed by', 'Amendment made', 'Workers re-inducted'],
        count: 6,
      },
      { kind: 'heading', number: '04', title: 'Scope of Works' },
      { kind: 'fields', rows: [{ label: 'Works covered by this SWMS', value: null }] },
      {
        kind: 'para',
        text: 'For example: installation of gates, garage doors, roller doors and shutters; motor installation; servicing and repair. Amend to match the task.',
      },
      { kind: 'heading', number: '05', title: 'PPE Required' },
      {
        kind: 'checkboxes',
        items: [
          'High-visibility clothing',
          'Safety glasses',
          'Hard hat',
          'Safety footwear',
          'Gloves',
          'Hearing protection',
          'Respiratory protection',
          'Face shield',
          'Welding helmet and apron',
          'Fall arrest harness',
          'Sun protection',
          'Other',
        ],
      },
      { kind: 'heading', number: '06', title: 'High-Risk Construction Work' },
      {
        kind: 'para',
        text: 'Tick every category of high-risk construction work this SWMS covers. A SWMS is required by the WHS Regulation for each of these activities.',
      },
      {
        kind: 'checkboxes',
        items: [
          'A risk of a person falling more than 2 metres',
          'Work on a telecommunications tower',
          'Demolition of a load-bearing structure',
          'Likely disturbance of asbestos',
          'Temporary load-bearing support for structural alterations',
          'Work in or near a confined space',
          'Work in a shaft or trench deeper than 1.5 m, or in a tunnel',
          'Use of explosives',
          'Work on or near pressurised gas mains or piping',
          'Work on or near chemical, fuel or refrigerant lines',
          'Work on or near energised electrical installations or services',
          'Work in an area that may have a contaminated or flammable atmosphere',
          'Tilt-up or precast concrete work',
          'Work on, in or adjacent to a road, railway, shipping lane or other traffic corridor in use',
          'Work in an area with movement of powered mobile plant',
          'Work in an area with artificial extremes of temperature',
          'Work in or near water or other liquid involving a risk of drowning',
          'Diving work',
        ],
      },
      { kind: 'heading', number: '07', title: 'Plant, Equipment and Hazardous Chemicals' },
      {
        kind: 'table',
        head: ['Plant and equipment to be used', 'Inspected', 'Test tag current'],
        rows: [
          ['Various hand tools', '', ''],
          ['Various electric / battery operated tools', '', ''],
          ['Concrete saw', '', ''],
          ['Welder', '', ''],
          ['Platform ladders', '', ''],
          ['EWP', '', ''],
        ],
      },
      {
        kind: 'blankRows',
        head: ['Hazardous chemical', 'SDS attached', 'Issue date', 'Doc reference'],
        count: 5,
      },
      { kind: 'heading', number: '08', title: 'Pre-Start Requirements and Authorisations' },
      {
        kind: 'checkboxes',
        items: [
          'Construction induction card',
          'Vehicle pre-start inspection',
          'Toolbox talk / pre-start',
          'Risk assessment / hazard identification',
          'Site specific induction',
          "Driver's licence",
          "Plant operator's licence / VOC",
          'Work safely at heights training',
          'Boom-type EWP licence (11 m or more)',
          'Trade licence',
          'Hot work permit',
          'Working at heights permit',
        ],
      },
      { kind: 'heading', number: '09', title: 'Legislation, Codes of Practice and Standards' },
      {
        kind: 'para',
        text: 'Tick the instruments that apply to the works. References below are to New South Wales instruments; substitute the equivalent for your jurisdiction if you operate elsewhere.',
      },
      { kind: 'para', text: 'Legislation and codes of practice' },
      {
        kind: 'checkboxes',
        items: [
          'Work Health and Safety Act 2011',
          'Work Health and Safety Regulation 2017',
          'Construction Work CoP',
          'Managing the Risk of Falls at Workplaces CoP',
          'Managing Electrical Risks in the Workplace CoP',
          'Managing Risks of Plant CoP',
          'Hazardous Manual Tasks CoP',
          'First Aid in the Workplace CoP',
          'Managing Noise and Preventing Hearing Loss CoP',
          'Welding Processes CoP',
          'WHS Consultation, Cooperation and Coordination CoP',
          'Managing the risk of respirable crystalline silica',
          'How to Manage Work Health and Safety Risks CoP',
          'Confined Spaces CoP',
          'How to Manage and Control Asbestos in the Workplace CoP',
          'Managing the Work Environment and Facilities CoP',
        ],
      },
      { kind: 'para', text: 'Australian Standards' },
      {
        kind: 'checkboxes',
        items: [
          'AS/ISO 31000 — Risk management',
          'AS/NZS 3000 — Electrical installations (wiring rules)',
          'AS/NZS 3760 — In-service inspection and testing of electrical equipment',
          'AS/NZS 3012 — Electrical installations, construction and demolition sites',
          'AS/NZS 1892 — Portable ladders',
          'AS/NZS 2210 — Occupational protective footwear',
          'AS/NZS 1336 — Eye and face protection',
          'AS/NZS 2616 — Occupational protective gloves',
          'AS/NZS 1269 — Occupational noise management',
          'AS/NZS 1801 — Occupational protective helmets',
          'AS 1674 — Safety in welding and allied processes',
          'AS 1841 — Portable fire extinguishers',
          'AS 1319 — Safety signs for the occupational environment',
          'AS/NZS 4576 — Guidelines for scaffolding',
        ],
      },
      {
        kind: 'important',
        title: 'Verify current editions',
        text: 'Australian Standards and Codes of Practice are periodically revised and withdrawn. Confirm the current designation and edition of each standard you rely on before issuing this SWMS to a principal contractor.',
      },
      { kind: 'heading', number: '10', title: 'Risk Matrix' },
      {
        kind: 'table',
        head: [
          '',
          'Consequence',
          'Almost certain (A)',
          'Likely (B)',
          'Possible (C)',
          'Unlikely (D)',
          'Rare (E)',
        ],
        rows: [
          [
            '1',
            'Catastrophic — fatality or permanent disability; toxic release of chemicals; long-term or irreversible environmental impact; loss of facilities; very high financial loss',
            'E (25)',
            'E (24)',
            'E (22)',
            'E (19)',
            'H (15)',
          ],
          [
            '2',
            'Major — long-term illness or serious injury; serious but reversible environmental impact; major property damage; loss of production; high financial loss',
            'E (23)',
            'E (21)',
            'E (18)',
            'H (14)',
            'M (10)',
          ],
          [
            '3',
            'Moderate — medical treatment requiring up to several days off work; reversible environmental impact; significant property damage; medium to high financial loss',
            'E (20)',
            'H (17)',
            'H (13)',
            'M (9)',
            'M (6)',
          ],
          [
            '4',
            'Minor — minor injury requiring first aid; minor reversible environmental impact; moderate property damage; low to medium financial loss',
            'H (16)',
            'H (12)',
            'M (8)',
            'L (5)',
            'L (3)',
          ],
          [
            '5',
            'Insignificant — no injuries or first aid only; minor property damage or environmental nuisance; very low financial loss',
            'M (11)',
            'M (7)',
            'L (4)',
            'L (2)',
            'L (1)',
          ],
        ],
      },
      {
        kind: 'table',
        head: ['E — Extreme', 'H — High', 'M — Medium', 'L — Low'],
        rows: [
          [
            'Urgent. Immediate action required.',
            'Highest management decision required urgently.',
            'Follow management instructions.',
            'Monitor. May not require immediate attention.',
          ],
        ],
      },
      {
        kind: 'para',
        text: 'Hierarchy of control — highest protection to lowest: 1. Elimination 2. Substitution 3. Isolation 4. Engineering 5. Administration 6. PPE',
      },
      { kind: 'heading', number: '11', title: 'Job Safety Analysis' },
      {
        kind: 'para',
        text: 'Residual risk assumes every control listed is actually in place. Where a control cannot be applied, stop and reassess before continuing.',
      },
      {
        kind: 'table',
        head: [
          'Activity',
          'Potential hazard',
          'L',
          'C',
          'Risk',
          'Control measures',
          'Residual',
          'Type',
          'Responsible',
        ],
        rows: [
          [
            'Site specific induction',
            'Miscommunication; unaware of emergency procedures',
            'C',
            '3',
            'H13',
            'Workers complete a site-specific induction before starting on site. Emergency procedures, muster point and first aid kit location confirmed.',
            'D3 / M9',
            'Admin',
            'All workers',
          ],
          [
            'Prepare for task',
            'Lack of consultation; unqualified personnel; changed conditions',
            'C',
            '3',
            'H13',
            'Pre-start meeting held and all site hazards identified. Tasks undertaken only by personnel assessed as competent. If conditions change, reassess using the additional hazards page at the back of this SWMS.',
            'D3 / M9',
            'Admin',
            'All workers',
          ],
          [
            'Site establishment',
            'Access and egress — struck by moving vehicles or plant',
            'C',
            '2',
            'E18',
            'Observe posted speed limits. Establish exclusion zones and signage. Spotter used for deliveries. Unload within the work area, away from public access.',
            'E2 / M10',
            'Admin',
            'Licensed operator',
          ],
          [
            '',
            'Slips, trips, housekeeping',
            'C',
            '3',
            'H13',
            'Worker access clearly defined. Public space kept clear of rubbish, debris and tools. Housekeeping maintained; barricades and access ways continually assessed.',
            'D3 / M9',
            'Admin',
            'All workers',
          ],
          [
            '',
            'Exposure to the elements — UV, heat, cold, wet',
            'C',
            '3',
            'H13',
            'Hi-vis and UV protective clothing, sunscreen, hydration and rest breaks on hot days. Wet weather gear provided. Sunglasses and wide-brimmed hats where practicable.',
            'C4 / M8',
            'PPE',
            'All workers',
          ],
          [
            'Manual handling',
            'Musculoskeletal injury lifting motors, doors, shutters',
            'C',
            '3',
            'H13',
            'Use mechanical aids where available. Hold loads close to the body. Team lift heavy components. Store loads between knee and shoulder height. Vary tasks and rotate staff on repetitive work.',
            'C4 / M8',
            'Admin',
            'All workers',
          ],
          [
            '',
            'Pinch points and crush injuries when lowering and stacking',
            'C',
            '3',
            'H13',
            'Allow room for fingers. Ensure the object is secure when put down. Riggers gloves, safety boots and safety glasses worn. Ask for assistance when required.',
            'D3 / M9',
            'PPE',
            'All workers',
          ],
          [
            'Ladders and work at height',
            'Damaged or worn ladder; fall from height',
            'C',
            '3',
            'H13',
            'Inspect for splits, cracks and wear; clean of oil and grease. Non-slip feet fitted and sound. Unsafe ladders removed from site. Industrial rating of 120 kg or more on construction sites.',
            'D3 / M9',
            'Eng / Admin',
            'Competent workers',
          ],
          [
            '',
            'Unsafe work from ladders',
            'C',
            '2',
            'E18',
            'Three points of contact at all times. Face the ladder when climbing or descending. Do not over-reach — get down and move the ladder. Extend at least 1 m past the point of access. Set at 1 out for every 4 up on firm, stable ground. Do not block up under the feet — use a ladder leveller.',
            'E2 / M10',
            'Eng / Admin',
            'Competent workers',
          ],
          [
            '',
            'Trestle, plank and portable work platform use',
            'C',
            '2',
            'E18',
            'Inspect before use; do not use damaged equipment. Full open position, four legs firm and level, secured against movement. Platform not higher than 5 m. Working platforms at least 450 mm wide. Minimum 250 mm plank overhang at each end.',
            'E2 / M10',
            'Eng / Admin',
            'Competent workers',
          ],
          [
            'Elevated work platform and scissor lift',
            'Operator competency; fall from EWP; tipping over, overloading',
            'C',
            '3',
            'H13',
            'Boom length 11 m or more requires a High Risk Work Licence (class WP). Below 11 m, operators must have completed training. Maintain contact with the operator before approaching. SWL never exceeded. An EWP is never used as a substitute for a forklift, crane or hoist.',
            'D3 / M9',
            'Admin',
            'Licensed workers',
          ],
          [
            '',
            'Working from the platform; falling tools',
            'C',
            '3',
            'H13',
            'Do not stand on railings or boxes to gain height — reposition the platform. Do not exit the platform while raised. Tools tethered or secured. Operations cease in high wind, rain or hail pending reassessment. Confirm no-go zones with the supply authority where electrical hazards are present.',
            'D3 / M9',
            'Isol / Admin / PPE',
            'Licensed workers',
          ],
          [
            '',
            'Emergency rescue from height',
            'C',
            '3',
            'H13',
            'All persons in the platform instructed and competent in rescue. Summon assistance and call 000 if emergency services are required. Lower the basket from the operator console, or use ground controls, or a second EWP if disabled. Advise site management.',
            'D3 / M9',
            'Admin',
            'Licensed workers',
          ],
          [
            'Hand and power tools',
            'Electrocution from damaged tools or leads',
            'C',
            '2',
            'E18',
            'Check casing for damage, cracks and missing screws. Inspect lead and plug; current test tag attached. Do not use damaged, incomplete or out-of-test equipment — quarantine and arrange repair. Leads kept off wet ground and elevated on insulated hangers.',
            'E2 / M10',
            'Admin',
            'Competent workers',
          ],
          [
            '',
            'Cuts, entanglement, flying debris, noise',
            'C',
            '3',
            'H13',
            'Guards fitted and operating correctly. Blade or cutter suited to the task and inspected for cracks. Close-fitting safety glasses and gloves worn. Loose clothing, hair and jewellery secured around rotating tools. Hearing protection where noise levels are exceeded.',
            'C4 / M8',
            'Eng / PPE',
            'Competent workers',
          ],
          [
            '',
            'Angle grinder — kick back, sparks, fire',
            'C',
            '3',
            'H13',
            'Double eye protection: face shield and safety glasses. Firm grip maintained against kick back. Area cleared of combustibles and an extinguisher kept nearby. A hot work permit may be required before commencing.',
            'C4 / M8',
            'PPE / Admin',
            'Competent workers',
          ],
          [
            '',
            'Tools used for energised electrical work',
            'C',
            '2',
            'E18',
            'Tools used on or near exposed energised parts must be non-conductive or insulated. Inspect before use and discard if insulation is faulty. Test instruments confirmed appropriate and functioning. Insulating mat provided underfoot.',
            'E2 / M10',
            'Eng / Admin',
            'Licensed workers',
          ],
          [
            'Hot works — welding and cutting',
            'Fire, burns, eye injury',
            'C',
            '3',
            'H13',
            'Permit to work obtained and authorised before commencing hot work. Area isolated and cleared of combustible material. Flashback arrestors fitted at cylinder and torch. Cylinders secured upright. At least one charged 2.5 kg extinguisher at the work area with a current test tag. Welding screens used to protect others.',
            'C4 / M8',
            'Admin / PPE',
            'Competent workers',
          ],
          [
            '',
            'Toxic fumes and asphyxiation',
            'C',
            '3',
            'H13',
            'Adequate natural or mechanical ventilation. Respiratory protection where ventilation is inadequate or toxic fumes may be present. Safety Data Sheet available and gases stored as per the SDS.',
            'C4 / M8',
            'Admin / PPE',
            'Competent workers',
          ],
          [
            'Cutting and drilling masonry — silica',
            'Respirable crystalline silica; silicosis, lung cancer',
            'C',
            '2',
            'E18',
            'Use wet cutting or on-tool extraction. Do not rely on sight to judge airborne dust. Fit-tested P2 respirator as a minimum; full-face P3 subject to risk assessment. Rotate staff away from dusty areas. Cordon the area and warn other trades. Class M or H vacuum used to remove dust.',
            'E2 / M10',
            'Admin / PPE',
            'Competent workers',
          ],
          [
            'Motors and drives',
            'Unsafe motor — loose or damaged parts',
            'C',
            '3',
            'H13',
            'Check mounting bolts and screws are in place and tightened. Do not use if faulty or damaged. Inspect regularly and tighten loose parts.',
            'D3 / M10',
            'Admin',
            'Competent workers',
          ],
          [
            '',
            'Electric shock during setup and testing',
            'C',
            '2',
            'E18',
            'De-energise and make safe all electrical contacts before commencing. Electrician to test. Keep motor units clear of standing water and connect through an RCD. Leads kept off the ground. Motor not energised prior to testing.',
            'E2 / M10',
            'Eng / Admin',
            'Licensed electrician',
          ],
          [
            '',
            'Cleaning and maintenance — motor failure',
            'C',
            '3',
            'H13',
            "Keep units clean of dirt and waste in cooling fins. Follow the manufacturer's instructions when servicing.",
            'D3 / M9',
            'Admin',
            'Competent workers',
          ],
          [
            'Hanging roller doors and gates',
            'Door falling during mounting; fall from height',
            'C',
            '3',
            'H13',
            'Do not remove the protective wrap from the door until it is in position and the spring is tensioned. Lift manually with two persons or use mechanical aids. Fit U-bolts immediately to prevent the door falling.',
            'D3 / M9',
            'Admin / Isolate',
            'Competent workers',
          ],
          [
            '',
            'Incorrect positioning and spring tensioning',
            'C',
            '3',
            'H13',
            "Follow the manufacturer's instructions to position the door and tighten U-bolts. Confirm the door is correctly positioned before final tightening. Ensure the chock holding the curtain down is correctly fitted and holding securely after tensioning, and is not dislodged when fitting stop brackets.",
            'D3 / M9',
            'Admin / Isolate',
            'Competent workers',
          ],
          [
            '',
            'Adjustment of the fitted door',
            'C',
            '3',
            'H13',
            'Two persons recommended. Do not loosen U-bolts unless the axle is held securely by a pipe wrench and held in position while bolts are loose. Correct wrench size; head and body kept clear of the wrench.',
            'C4 / M8',
            'Admin',
            'Competent workers',
          ],
          [
            '',
            'Fitting guides and controls — sharp edges',
            'C',
            '3',
            'H13',
            'Exercise care handling door guides; sharp edges may be present. Safety boots, gloves, long sleeves and trousers worn.',
            'C4 / M8',
            'Admin / PPE',
            'Competent workers',
          ],
          [
            'Clean up and demobilisation',
            'Dust and eye injury when sweeping; slips and manual handling',
            'C',
            '3',
            'H13',
            'Training provided in hazardous substances and PPE. Dust mask and eye protection worn. Travel paths and loading areas kept clear. Waste disposed of in the bins provided; recycle where possible.',
            'D3 / M9',
            'Admin / PPE',
            'All workers',
          ],
        ],
      },
      { kind: 'heading', number: '12', title: 'Additional Site-Specific Hazards' },
      {
        kind: 'para',
        text: 'Record any hazard, risk or control not covered elsewhere in this SWMS — arising from task observation, reassessment, a change in method, an incident, consultation with the work crew, or circumstances where the SWMS cannot be applied as documented.',
      },
      {
        kind: 'blankRows',
        head: ['Activity', 'Potential hazard', 'L', 'C', 'Risk', 'Control measures', 'Residual', 'Responsible'],
        count: 6,
      },
      { kind: 'signature', parties: ['Prepared by', 'Approved by'] },
    ],
  },
}

export function contentFor(code: string): DocumentContent | null {
  return DOCUMENT_CONTENT[code] ?? null
}

/** Codes whose content has been transcribed and can be issued. */
export function availableCodes(): string[] {
  return Object.keys(DOCUMENT_CONTENT)
}
